substitutions:
  _IMAGE_NAME: profile-svc-jib

steps:

- # Uses the Cloud Builder Maven image since it is cached.
  name: gcr.io/cloud-builders/mvn
  dir: /root
  entrypoint: bash
  args:
  - -c
  - # Links the Docker config to /root/.docker/config.json so Jib picks it up.
    # Note that this is only a temporary workaround.
    # See https://github.com/GoogleContainerTools/jib/pull/1479.
    |
    mkdir .docker &&
    ln -s $$HOME/.docker/config.json .docker/config.json

  volumes:
  - name: user.home
    path: /root

- # Uses the Cloud Builder Maven image.
  name: gcr.io/cloud-builders/mvn
  args:
  # Compiles the application.
  - -B
  - compile
  # To use a specific version, configure the plugin in the pom.xml.
  - com.google.cloud.tools:jib-maven-plugin:build
  - -Dmaven.test.skip=true

  # Sets the target image reference to push to.
  - -Dimage=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}

  volumes:
  - name: user.home
    path: /root

- # update the deployment
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/${_APP_DEPLOYMENT_NAME}', 'profile-svc=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}', '-n', '${_APP_CONTAINER_CLUSTER}' ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_APP_CONTAINER_CLUSTER}'

