# tomcat configurations
server:
  port: 8080
  tomcat:
    max-threads: 250
    # print access log to console for debugging
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:

# spring configurations
spring:
  application:
    name: profile-svc

# actuator related
management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /
      path-mapping:
        prometheus: metrics
svc:
  message: Hello hello

