apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: profile-svc
  labels:
    app: profile-svc
    k8s-app: profile-svc
spec:
  selector:
    matchLabels:
      app: profile-svc
  endpoints:
    - port: web
      scheme: http
      path: '/actuator/prometheus'
      interval: 15s
      honorLabels: true
